"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CUSTOMER_LIFECYCLE_STAGES = exports.CUSTOMER_IDENTITY_TYPES = exports.CUSTOMER_IDENTITY_SOURCES = exports.CUSTOMER_IDENTITY_RESOLUTION_STATUSES = exports.CUSTOMER_IDENTITY_CONFIDENCE_LEVELS = exports.resolveCustomerCandidate = exports.readPrestashopOrderCandidate = exports.readPrestashopCustomerCandidate = exports.readPrestashopAddressCandidate = exports.readLegacyInboundCandidate = exports.readLegacyConversationCandidate = exports.normalizeWaId = exports.normalizePhoneChile = exports.normalizeLooseIdentifier = exports.normalizeIdentityValue = exports.normalizeEmail = exports.buildChilePhoneCandidates = exports.CUSTOMER_STRONG_IDENTITY_TYPES = exports.CUSTOMER_PROVISIONAL_IDENTITY_TYPES = exports.CUSTOMER_NO_MERGE_REASONS = exports.CUSTOMER_IDENTITY_PRECEDENCE = exports.CUSTOMER_DEFAULT_READ_ONLY_OPTIONS = exports.CUSTOMER_DEFAULT_IDENTITY_SOURCE = exports.CUSTOMER_DEFAULT_IDENTITY_CONFIDENCE = void 0;
var constants_1 = require("./constants");
Object.defineProperty(exports, "CUSTOMER_DEFAULT_IDENTITY_CONFIDENCE", { enumerable: true, get: function () { return constants_1.CUSTOMER_DEFAULT_IDENTITY_CONFIDENCE; } });
Object.defineProperty(exports, "CUSTOMER_DEFAULT_IDENTITY_SOURCE", { enumerable: true, get: function () { return constants_1.CUSTOMER_DEFAULT_IDENTITY_SOURCE; } });
Object.defineProperty(exports, "CUSTOMER_DEFAULT_READ_ONLY_OPTIONS", { enumerable: true, get: function () { return constants_1.CUSTOMER_DEFAULT_READ_ONLY_OPTIONS; } });
Object.defineProperty(exports, "CUSTOMER_IDENTITY_PRECEDENCE", { enumerable: true, get: function () { return constants_1.CUSTOMER_IDENTITY_PRECEDENCE; } });
Object.defineProperty(exports, "CUSTOMER_NO_MERGE_REASONS", { enumerable: true, get: function () { return constants_1.CUSTOMER_NO_MERGE_REASONS; } });
Object.defineProperty(exports, "CUSTOMER_PROVISIONAL_IDENTITY_TYPES", { enumerable: true, get: function () { return constants_1.CUSTOMER_PROVISIONAL_IDENTITY_TYPES; } });
Object.defineProperty(exports, "CUSTOMER_STRONG_IDENTITY_TYPES", { enumerable: true, get: function () { return constants_1.CUSTOMER_STRONG_IDENTITY_TYPES; } });
var normalize_1 = require("./normalize");
Object.defineProperty(exports, "buildChilePhoneCandidates", { enumerable: true, get: function () { return normalize_1.buildChilePhoneCandidates; } });
Object.defineProperty(exports, "normalizeEmail", { enumerable: true, get: function () { return normalize_1.normalizeEmail; } });
Object.defineProperty(exports, "normalizeIdentityValue", { enumerable: true, get: function () { return normalize_1.normalizeIdentityValue; } });
Object.defineProperty(exports, "normalizeLooseIdentifier", { enumerable: true, get: function () { return normalize_1.normalizeLooseIdentifier; } });
Object.defineProperty(exports, "normalizePhoneChile", { enumerable: true, get: function () { return normalize_1.normalizePhoneChile; } });
Object.defineProperty(exports, "normalizeWaId", { enumerable: true, get: function () { return normalize_1.normalizeWaId; } });
var sourceReaders_1 = require("./sourceReaders");
Object.defineProperty(exports, "readLegacyConversationCandidate", { enumerable: true, get: function () { return sourceReaders_1.readLegacyConversationCandidate; } });
Object.defineProperty(exports, "readLegacyInboundCandidate", { enumerable: true, get: function () { return sourceReaders_1.readLegacyInboundCandidate; } });
Object.defineProperty(exports, "readPrestashopAddressCandidate", { enumerable: true, get: function () { return sourceReaders_1.readPrestashopAddressCandidate; } });
Object.defineProperty(exports, "readPrestashopCustomerCandidate", { enumerable: true, get: function () { return sourceReaders_1.readPrestashopCustomerCandidate; } });
Object.defineProperty(exports, "readPrestashopOrderCandidate", { enumerable: true, get: function () { return sourceReaders_1.readPrestashopOrderCandidate; } });
var resolveCustomerCandidate_1 = require("./resolveCustomerCandidate");
Object.defineProperty(exports, "resolveCustomerCandidate", { enumerable: true, get: function () { return resolveCustomerCandidate_1.resolveCustomerCandidate; } });
var types_1 = require("./types");
Object.defineProperty(exports, "CUSTOMER_IDENTITY_CONFIDENCE_LEVELS", { enumerable: true, get: function () { return types_1.CUSTOMER_IDENTITY_CONFIDENCE_LEVELS; } });
Object.defineProperty(exports, "CUSTOMER_IDENTITY_RESOLUTION_STATUSES", { enumerable: true, get: function () { return types_1.CUSTOMER_IDENTITY_RESOLUTION_STATUSES; } });
Object.defineProperty(exports, "CUSTOMER_IDENTITY_SOURCES", { enumerable: true, get: function () { return types_1.CUSTOMER_IDENTITY_SOURCES; } });
Object.defineProperty(exports, "CUSTOMER_IDENTITY_TYPES", { enumerable: true, get: function () { return types_1.CUSTOMER_IDENTITY_TYPES; } });
Object.defineProperty(exports, "CUSTOMER_LIFECYCLE_STAGES", { enumerable: true, get: function () { return types_1.CUSTOMER_LIFECYCLE_STAGES; } });
