export {
  COMMERCIAL_SANDBOX_AUTONOMY_ALLOWED_ACTION_TYPES,
  COMMERCIAL_SANDBOX_AUTONOMY_ALLOWED_CHANNEL,
  COMMERCIAL_SANDBOX_AUTONOMY_ALLOWED_RISK_LEVEL,
  COMMERCIAL_SANDBOX_AUTONOMY_DEFAULT_MESSAGE_LIMIT
} from "./types";

export const BRAIN_AUTONOMOUS_SANDBOX_ENABLED = "BRAIN_AUTONOMOUS_SANDBOX_ENABLED" as const;
export const BRAIN_AUTONOMOUS_REPLY_ENABLED = "BRAIN_AUTONOMOUS_REPLY_ENABLED" as const;
export const BRAIN_AUTONOMOUS_TEST_WA_IDS = "BRAIN_AUTONOMOUS_TEST_WA_IDS" as const;
export const BRAIN_AUTONOMOUS_ALLOWED_ACTION_TYPES = "BRAIN_AUTONOMOUS_ALLOWED_ACTION_TYPES" as const;
export const BRAIN_AUTONOMOUS_MAX_RISK_LEVEL = "BRAIN_AUTONOMOUS_MAX_RISK_LEVEL" as const;
