export const COMMERCIAL_OBJECTIVE_TYPES = [
  "DISCOVER_PRODUCTS",
  "COMPARE_PRODUCTS",
  "RECOMMEND_PRODUCTS",
  "SELECT_PRODUCTS",
  "CHANGE_QUANTITY",
  "SET_DESTINATION",
  "GET_SHIPPING_QUOTE",
  "SELECT_SHIPPING_OPTION",
  "CREATE_QUOTE",
  "HANDOFF"
] as const;

export type CommercialObjectiveType = (typeof COMMERCIAL_OBJECTIVE_TYPES)[number];
