CREATE TABLE IF NOT EXISTS brain_message_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dedupe_key VARCHAR(191) NOT NULL,
  channel VARCHAR(32) NOT NULL DEFAULT 'whatsapp',
  direction VARCHAR(16) NOT NULL DEFAULT 'outbound',
  status VARCHAR(32) NOT NULL DEFAULT 'planned',
  source VARCHAR(64) NULL,
  source_request_id VARCHAR(128) NULL,
  source_agent_name VARCHAR(64) NULL,
  source_agent_version VARCHAR(64) NULL,
  wa_id VARCHAR(64) NULL,
  phone_number_id VARCHAR(64) NULL,
  conversation_case_id BIGINT NULL,
  message_text TEXT NULL,
  message_hash VARCHAR(64) NULL,
  meta_payload_json JSON NULL,
  provider_message_id VARCHAR(128) NULL,
  error_code VARCHAR(64) NULL,
  error_message TEXT NULL,
  planned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_at DATETIME NULL,
  sent_at DATETIME NULL,
  failed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_brain_message_outbox_dedupe_key (dedupe_key),
  KEY idx_brain_outbox_status_created (status, created_at),
  KEY idx_brain_outbox_wa_created (wa_id, created_at),
  KEY idx_brain_outbox_case_created (conversation_case_id, created_at),
  KEY idx_brain_outbox_provider_message_id (provider_message_id)
);
