export const DEFAULT_RECOMMENDATION_LIMIT = 5;
export const SECONDARY_RECOMMENDATION_LIMIT = 5;
export const MAX_RECOMMENDATION_LIMIT = 20;
export const RECOMMENDATION_LIMIT_OPTIONS = [5, 10, 20] as const;
