INSERT INTO master_customer (id, firstname, lastname, email, platform_origin)
VALUES
  (1, 'Camila', 'Rojas', 'camila.rojas@example.test', 'hub')
ON DUPLICATE KEY UPDATE
  firstname = VALUES(firstname),
  lastname = VALUES(lastname),
  email = VALUES(email),
  platform_origin = VALUES(platform_origin);

INSERT INTO n8n_conversation_cases (
  conversation_case_id,
  active_case_key,
  wa_id,
  contact_name,
  phone_number_id,
  department,
  status,
  priority,
  service_code,
  requires_human,
  bot_replied,
  final_action,
  ai_blocked,
  lifecycle_status,
  id_customer,
  source_table,
  source_id,
  whatsapp_window_open,
  last_message_at,
  created_at,
  updated_at,
  message_count,
  last_message,
  email,
  phone_normalized,
  first_message_at
)
VALUES
  (
    9001,
    'case-9001',
    '56900000001',
    'Camila Rojas',
    'phone-test-001',
    'ventas',
    'open',
    'high',
    'onboarding',
    1,
    0,
    'pending_lookup',
    0,
    'active',
    1,
    'n8n_vw_hub_cases',
    9001,
    1,
    '2026-06-24 08:05:00',
    '2026-06-24 08:00:00',
    '2026-06-24 08:05:00',
    1,
    'Hola, necesito crear mi cuenta',
    'camila.rojas@example.test',
    '56900000001',
    '2026-06-24 08:00:00'
  )
ON DUPLICATE KEY UPDATE
  active_case_key = VALUES(active_case_key),
  wa_id = VALUES(wa_id),
  contact_name = VALUES(contact_name),
  phone_number_id = VALUES(phone_number_id),
  department = VALUES(department),
  status = VALUES(status),
  priority = VALUES(priority),
  service_code = VALUES(service_code),
  requires_human = VALUES(requires_human),
  bot_replied = VALUES(bot_replied),
  final_action = VALUES(final_action),
  ai_blocked = VALUES(ai_blocked),
  lifecycle_status = VALUES(lifecycle_status),
  id_customer = VALUES(id_customer),
  source_table = VALUES(source_table),
  source_id = VALUES(source_id),
  whatsapp_window_open = VALUES(whatsapp_window_open),
  last_message_at = VALUES(last_message_at),
  created_at = VALUES(created_at),
  updated_at = VALUES(updated_at),
  message_count = VALUES(message_count),
  last_message = VALUES(last_message),
  email = VALUES(email),
  phone_normalized = VALUES(phone_normalized),
  first_message_at = VALUES(first_message_at);

INSERT INTO n8n_conversation_messages (
  id,
  conversation_case_id,
  message_id,
  wa_id,
  phone_number_id,
  direction,
  message_direction,
  message_type,
  message_text,
  text,
  body,
  message,
  content,
  raw_text,
  final_action,
  status,
  intent,
  department,
  occurred_at,
  created_at,
  updated_at,
  source_table,
  source_id,
  provider_message_id,
  technical_origin
)
VALUES
  (
    9001,
    9001,
    'test-msg-9001',
    '56900000001',
    'phone-test-001',
    'inbound',
    'inbound',
    'text',
    'Hola, necesito crear mi cuenta',
    'Hola, necesito crear mi cuenta',
    'Hola, necesito crear mi cuenta',
    'Hola, necesito crear mi cuenta',
    'Hola, necesito crear mi cuenta',
    'Hola, necesito crear mi cuenta',
    'manual_operator_reply',
    'delivered',
    'create_account',
    'ventas',
    '2026-06-24 08:02:00',
    '2026-06-24 08:02:00',
    '2026-06-24 08:02:00',
    'n8n_conversation_messages',
    9001,
    'provider-test-9001',
    'legacy_n8n'
  )
ON DUPLICATE KEY UPDATE
  message_id = VALUES(message_id),
  wa_id = VALUES(wa_id),
  phone_number_id = VALUES(phone_number_id),
  direction = VALUES(direction),
  message_direction = VALUES(message_direction),
  message_type = VALUES(message_type),
  message_text = VALUES(message_text),
  text = VALUES(text),
  body = VALUES(body),
  message = VALUES(message),
  content = VALUES(content),
  raw_text = VALUES(raw_text),
  final_action = VALUES(final_action),
  status = VALUES(status),
  intent = VALUES(intent),
  department = VALUES(department),
  occurred_at = VALUES(occurred_at),
  created_at = VALUES(created_at),
  updated_at = VALUES(updated_at),
  source_table = VALUES(source_table),
  source_id = VALUES(source_id),
  provider_message_id = VALUES(provider_message_id),
  technical_origin = VALUES(technical_origin);

INSERT INTO crm_customer_onboarding (
  conversation_case_id,
  wa_id,
  state,
  pending_action,
  pending_customer_confirmation,
  email,
  firstname,
  lastname,
  warnings_json,
  context_json
)
VALUES
  (
    '9001',
    '56900000001',
    'creation_offered',
    'create_customer',
    1,
    'camila.rojas@example.test',
    'Camila',
    'Rojas',
    JSON_ARRAY('seeded_for_tests'),
    JSON_OBJECT('scenario', 'minimal_test_data')
  )
ON DUPLICATE KEY UPDATE
  state = VALUES(state),
  pending_action = VALUES(pending_action),
  pending_customer_confirmation = VALUES(pending_customer_confirmation),
  email = VALUES(email),
  firstname = VALUES(firstname),
  lastname = VALUES(lastname),
  warnings_json = VALUES(warnings_json),
  context_json = VALUES(context_json);

