CREATE DATABASE IF NOT EXISTS crm_dev CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS crm_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS crm_legacy_fixture CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'crm_dev_admin'@'%' IDENTIFIED BY '';

GRANT SELECT, INSERT, UPDATE, DELETE ON crm_dev.* TO 'crm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON crm_test.* TO 'crm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON crm_legacy_fixture.* TO 'crm_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, CREATE VIEW, SHOW VIEW, TRIGGER ON crm_dev.* TO 'crm_dev_admin'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, CREATE VIEW, SHOW VIEW, TRIGGER ON crm_test.* TO 'crm_dev_admin'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, CREATE VIEW, SHOW VIEW, TRIGGER ON crm_legacy_fixture.* TO 'crm_dev_admin'@'%';

FLUSH PRIVILEGES;
