"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INITIAL_ALLOWED_OPPORTUNITY_TRANSITIONS = exports.TERMINAL_OPPORTUNITY_STATUSES = exports.OPPORTUNITY_OBJECTION_TYPES = exports.OPPORTUNITY_LOST_REASONS = exports.COMMERCIAL_TEMPERATURES = exports.COMMERCIAL_PRIORITIES = exports.COMMERCIAL_SIGNALS = exports.COMMERCIAL_INTENTS = exports.LEAD_SOURCES = exports.OPPORTUNITY_STAGES = exports.OPPORTUNITY_STATUSES = exports.LEAD_STATUSES = exports.COMMERCIAL_CONTEXT_RESULT_STATUSES = exports.COMMERCIAL_CONTEXT_COMPLETENESS = exports.COMMERCIAL_CONTEXT_WARNINGS = exports.COMMERCIAL_CONTEXT_STALE_THRESHOLD_MS = exports.COMMERCIAL_CONTEXT_MAX_RECENT_MESSAGES = exports.COMMERCIAL_CONTEXT_VERSION = void 0;
exports.COMMERCIAL_CONTEXT_VERSION = "brain.commercial.context.v1";
exports.COMMERCIAL_CONTEXT_MAX_RECENT_MESSAGES = 12;
exports.COMMERCIAL_CONTEXT_STALE_THRESHOLD_MS = 7 * 24 * 60 * 60 * 1000;
exports.COMMERCIAL_CONTEXT_WARNINGS = [
    "missing_latest_customer_message",
    "missing_customer_reference",
    "missing_conversation_history",
    "missing_channel",
    "missing_commercial_entity",
    "stale_context",
    "identity_conflict",
    "ai_blocked",
    "human_owner_active",
    "unsupported_context_shape",
    "sanitization_applied"
];
exports.COMMERCIAL_CONTEXT_COMPLETENESS = ["complete", "partial", "minimal", "insufficient"];
exports.COMMERCIAL_CONTEXT_RESULT_STATUSES = ["success", "insufficient_context", "invalid_input"];
exports.LEAD_STATUSES = [
    "new",
    "contacted",
    "engaged",
    "qualifying",
    "qualified",
    "unqualified",
    "converted",
    "dormant",
    "archived",
];
exports.OPPORTUNITY_STATUSES = [
    "new",
    "engaged",
    "qualifying",
    "quote_pending",
    "quote_ready_for_review",
    "quote_sent",
    "waiting_customer",
    "followup_scheduled",
    "negotiation",
    "stalled",
    "won",
    "lost",
    "cancelled",
    "archived",
];
exports.OPPORTUNITY_STAGES = [
    "discovery",
    "qualification",
    "solution_fit",
    "quotation",
    "negotiation",
    "closing",
    "post_sale_handoff",
];
exports.LEAD_SOURCES = [
    "whatsapp_inbound",
    "whatsapp_outbound",
    "ecommerce",
    "pos",
    "manual_hub",
    "referral",
    "campaign",
    "email",
    "phone_call",
    "appsheet_import",
    "legacy_import",
    "unknown",
];
exports.COMMERCIAL_INTENTS = [
    "product_inquiry",
    "product_recommendation",
    "price_request",
    "stock_request",
    "quote_request",
    "delivery_request",
    "discount_request",
    "bulk_purchase",
    "equipment_project",
    "maintenance_request",
    "assembly_request",
    "post_sale_request",
    "general_information",
    "unknown",
];
exports.COMMERCIAL_SIGNALS = [
    "replied",
    "no_reply",
    "left_on_seen",
    "high_intent",
    "medium_intent",
    "low_intent",
    "asks_price",
    "asks_stock",
    "asks_delivery",
    "asks_discount",
    "asks_quote",
    "shares_requirements",
    "shares_budget",
    "shares_deadline",
    "objection_price",
    "objection_timing",
    "objection_trust",
    "objection_product_fit",
    "human_requested",
    "purchase_confirmed",
    "rejection_explicit",
    "conversation_inactive",
];
exports.COMMERCIAL_PRIORITIES = [
    "low",
    "normal",
    "high",
    "urgent",
];
exports.COMMERCIAL_TEMPERATURES = [
    "cold",
    "warm",
    "hot",
    "unknown",
];
exports.OPPORTUNITY_LOST_REASONS = [
    "price",
    "no_response",
    "chose_competitor",
    "unavailable_stock",
    "delivery_timing",
    "product_not_suitable",
    "budget_unavailable",
    "postponed",
    "duplicate",
    "invalid_lead",
    "explicit_rejection",
    "unknown",
];
exports.OPPORTUNITY_OBJECTION_TYPES = [
    "price",
    "timing",
    "trust",
    "stock",
    "delivery",
    "product_fit",
    "approval_required",
    "competitor",
    "unknown",
];
exports.TERMINAL_OPPORTUNITY_STATUSES = [
    "won",
    "lost",
    "cancelled",
    "archived",
];
exports.INITIAL_ALLOWED_OPPORTUNITY_TRANSITIONS = [
    {
        from: "new",
        to: "engaged",
        reason: "reply_or_clear_interest",
        source: "whatsapp_inbound",
        detectedAt: "",
        requiresEvidence: false,
        requiresApproval: false,
    },
    {
        from: "engaged",
        to: "qualifying",
        reason: "need_more_information",
        source: "brain",
        detectedAt: "",
        requiresEvidence: false,
        requiresApproval: false,
    },
    {
        from: "qualifying",
        to: "quote_pending",
        reason: "ready_for_quote_draft",
        source: "brain",
        detectedAt: "",
        requiresEvidence: false,
        requiresApproval: false,
    },
    {
        from: "quote_sent",
        to: "waiting_customer",
        reason: "quote_shared_waiting_reply",
        source: "brain",
        detectedAt: "",
        requiresEvidence: false,
        requiresApproval: false,
    },
    {
        from: "waiting_customer",
        to: "followup_scheduled",
        reason: "follow_up_planned",
        source: "brain",
        detectedAt: "",
        requiresEvidence: false,
        requiresApproval: false,
    },
    {
        from: "followup_scheduled",
        to: "negotiation",
        reason: "customer_reengaged",
        source: "brain",
        detectedAt: "",
        requiresEvidence: false,
        requiresApproval: false,
    },
    {
        from: "stalled",
        to: "engaged",
        reason: "reactivated",
        source: "brain",
        detectedAt: "",
        requiresEvidence: false,
        requiresApproval: false,
    },
    {
        from: "stalled",
        to: "lost",
        reason: "lost_due_to_no_progress_or_evidence",
        source: "brain",
        detectedAt: "",
        requiresEvidence: true,
        requiresApproval: true,
    },
];
