"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.sanitizeOutboxWorkerErrorMessage = exports.normalizeIsoTimestamp = exports.normalizeCommandText = exports.maskRecipientForAudit = exports.isTerminalOutboxStatus = exports.isRetryableTransportErrorCode = exports.isReclaimableOutboxStatus = exports.isRecoverableLeaseStatus = exports.isPermanentTransportErrorCode = exports.evaluateOutboxCandidate = exports.clone = exports.calculateOutboxRetrySchedule = exports.buildOutboxWorkerPlanKey = exports.buildOutboxWorkerPlanId = exports.buildOutboxAuditEventId = exports.buildFakeProviderMessageId = exports.addSecondsToIso = exports.OUTBOX_WORKER_VERSION = exports.OUTBOX_WORKER_TERMINAL_STATUSES = exports.OUTBOX_WORKER_RETRYABLE_FAILURE_CODES = exports.OUTBOX_WORKER_RECLAIMABLE_STATUSES = exports.OUTBOX_WORKER_RECOVERABLE_LEASE_STATUSES = exports.OUTBOX_WORKER_PLAN_TYPES = exports.OUTBOX_WORKER_PLAN_REASONS = exports.OUTBOX_WORKER_AUDIT_EVENT_TYPES = exports.OUTBOX_MESSAGE_TERMINAL_STATUSES = exports.OUTBOX_MESSAGE_STATUSES = exports.validateCommercialProposedAction = exports.validateCommercialOperatorReviewDraft = exports.validateCommercialExecutableCommandPreview = exports.validateCommercialActionDecision = exports.validateActionLifecycleTransition = exports.validateSalesAgentOutput = void 0;
__exportStar(require("./constants"), exports);
__exportStar(require("./followUpConstants"), exports);
__exportStar(require("./followUpTypes"), exports);
__exportStar(require("./operatorCopilotConstants"), exports);
__exportStar(require("./operatorCopilotTypes"), exports);
__exportStar(require("./salesAgentConstants"), exports);
__exportStar(require("./salesAgentTypes"), exports);
__exportStar(require("./types"), exports);
__exportStar(require("./context"), exports);
__exportStar(require("./sales-agent/runtimeTypes"), exports);
__exportStar(require("./sales-agent/providerTypes"), exports);
__exportStar(require("./sales-agent/promptBuilder"), exports);
__exportStar(require("./sales-agent/runSalesAgentDryRun"), exports);
__exportStar(require("./sales-agent/createSalesAgentRuntimeFailedSafe"), exports);
__exportStar(require("./sales-agent/providers"), exports);
__exportStar(require("./sales-agent/sanitizeSalesAgentOutput"), exports);
__exportStar(require("./sales-agent/createFailedSafeResult"), exports);
var validateSalesAgentOutput_1 = require("./sales-agent/validateSalesAgentOutput");
Object.defineProperty(exports, "validateSalesAgentOutput", { enumerable: true, get: function () { return validateSalesAgentOutput_1.validateSalesAgentOutput; } });
__exportStar(require("./policy"), exports);
__exportStar(require("./shadow"), exports);
__exportStar(require("./evaluation"), exports);
__exportStar(require("./review"), exports);
__exportStar(require("./operator-pilot"), exports);
__exportStar(require("./operational-loop"), exports);
__exportStar(require("./action-lifecycle/constants"), exports);
var action_lifecycle_1 = require("./action-lifecycle");
Object.defineProperty(exports, "validateActionLifecycleTransition", { enumerable: true, get: function () { return action_lifecycle_1.validateActionLifecycleTransition; } });
Object.defineProperty(exports, "validateCommercialActionDecision", { enumerable: true, get: function () { return action_lifecycle_1.validateCommercialActionDecision; } });
Object.defineProperty(exports, "validateCommercialExecutableCommandPreview", { enumerable: true, get: function () { return action_lifecycle_1.validateCommercialExecutableCommandPreview; } });
Object.defineProperty(exports, "validateCommercialOperatorReviewDraft", { enumerable: true, get: function () { return action_lifecycle_1.validateCommercialOperatorReviewDraft; } });
Object.defineProperty(exports, "validateCommercialProposedAction", { enumerable: true, get: function () { return action_lifecycle_1.validateCommercialProposedAction; } });
__exportStar(require("./follow-up-planner"), exports);
__exportStar(require("./follow-up-scheduling"), exports);
__exportStar(require("./follow-up-replanning"), exports);
__exportStar(require("./action-queue"), exports);
__exportStar(require("./autonomy-sandbox"), exports);
__exportStar(require("./execution-gate"), exports);
__exportStar(require("./autonomous-loop"), exports);
__exportStar(require("./scenario-simulator"), exports);
__exportStar(require("../messaging/whatsapp-transport"), exports);
var outbox_worker_1 = require("../messaging/outbox-worker");
Object.defineProperty(exports, "OUTBOX_MESSAGE_STATUSES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_MESSAGE_STATUSES; } });
Object.defineProperty(exports, "OUTBOX_MESSAGE_TERMINAL_STATUSES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_MESSAGE_TERMINAL_STATUSES; } });
Object.defineProperty(exports, "OUTBOX_WORKER_AUDIT_EVENT_TYPES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_AUDIT_EVENT_TYPES; } });
Object.defineProperty(exports, "OUTBOX_WORKER_PLAN_REASONS", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_PLAN_REASONS; } });
Object.defineProperty(exports, "OUTBOX_WORKER_PLAN_TYPES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_PLAN_TYPES; } });
Object.defineProperty(exports, "OUTBOX_WORKER_RECOVERABLE_LEASE_STATUSES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_RECOVERABLE_LEASE_STATUSES; } });
Object.defineProperty(exports, "OUTBOX_WORKER_RECLAIMABLE_STATUSES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_RECLAIMABLE_STATUSES; } });
Object.defineProperty(exports, "OUTBOX_WORKER_RETRYABLE_FAILURE_CODES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_RETRYABLE_FAILURE_CODES; } });
Object.defineProperty(exports, "OUTBOX_WORKER_TERMINAL_STATUSES", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_TERMINAL_STATUSES; } });
Object.defineProperty(exports, "OUTBOX_WORKER_VERSION", { enumerable: true, get: function () { return outbox_worker_1.OUTBOX_WORKER_VERSION; } });
Object.defineProperty(exports, "addSecondsToIso", { enumerable: true, get: function () { return outbox_worker_1.addSecondsToIso; } });
Object.defineProperty(exports, "buildFakeProviderMessageId", { enumerable: true, get: function () { return outbox_worker_1.buildFakeProviderMessageId; } });
Object.defineProperty(exports, "buildOutboxAuditEventId", { enumerable: true, get: function () { return outbox_worker_1.buildOutboxAuditEventId; } });
Object.defineProperty(exports, "buildOutboxWorkerPlanId", { enumerable: true, get: function () { return outbox_worker_1.buildOutboxWorkerPlanId; } });
Object.defineProperty(exports, "buildOutboxWorkerPlanKey", { enumerable: true, get: function () { return outbox_worker_1.buildOutboxWorkerPlanKey; } });
Object.defineProperty(exports, "calculateOutboxRetrySchedule", { enumerable: true, get: function () { return outbox_worker_1.calculateOutboxRetrySchedule; } });
Object.defineProperty(exports, "clone", { enumerable: true, get: function () { return outbox_worker_1.clone; } });
Object.defineProperty(exports, "evaluateOutboxCandidate", { enumerable: true, get: function () { return outbox_worker_1.evaluateOutboxCandidate; } });
Object.defineProperty(exports, "isPermanentTransportErrorCode", { enumerable: true, get: function () { return outbox_worker_1.isPermanentTransportErrorCode; } });
Object.defineProperty(exports, "isRecoverableLeaseStatus", { enumerable: true, get: function () { return outbox_worker_1.isRecoverableLeaseStatus; } });
Object.defineProperty(exports, "isReclaimableOutboxStatus", { enumerable: true, get: function () { return outbox_worker_1.isReclaimableOutboxStatus; } });
Object.defineProperty(exports, "isRetryableTransportErrorCode", { enumerable: true, get: function () { return outbox_worker_1.isRetryableTransportErrorCode; } });
Object.defineProperty(exports, "isTerminalOutboxStatus", { enumerable: true, get: function () { return outbox_worker_1.isTerminalOutboxStatus; } });
Object.defineProperty(exports, "maskRecipientForAudit", { enumerable: true, get: function () { return outbox_worker_1.maskRecipientForAudit; } });
Object.defineProperty(exports, "normalizeCommandText", { enumerable: true, get: function () { return outbox_worker_1.normalizeCommandText; } });
Object.defineProperty(exports, "normalizeIsoTimestamp", { enumerable: true, get: function () { return outbox_worker_1.normalizeIsoTimestamp; } });
Object.defineProperty(exports, "sanitizeOutboxWorkerErrorMessage", { enumerable: true, get: function () { return outbox_worker_1.sanitizeOutboxWorkerErrorMessage; } });
