INSERT INTO n8n_conversation_cases (
  conversation_case_id,
  active_case_key,
  wa_id,
  contact_name,
  phone_number_id,
  department,
  status,
  priority,
  service_code,
  requires_human,
  bot_replied,
  final_action,
  ai_blocked,
  lifecycle_status,
  id_order,
  id_customer,
  invoice_number,
  source_table,
  source_id,
  whatsapp_window_open,
  last_message_at,
  created_at,
  updated_at,
  closed_at,
  message_count,
  last_message,
  contact_id,
  email,
  phone,
  phone_normalized,
  first_message_at
)
VALUES
  (
    1001,
    'case-1001',
    '56900000001',
    'Camila Rojas',
    'phone-001',
    'ventas',
    'open',
    'high',
    'quote_requested',
    1,
    0,
    'handoff_to_human',
    0,
    'active',
    '5001',
    1,
    'INV-1001',
    'n8n_vw_hub_cases',
    1001,
    1,
    '2026-06-24 10:15:00',
    '2026-06-24 10:00:00',
    '2026-06-24 10:15:00',
    NULL,
    2,
    'Hola, necesito ayuda con mi cotización',
    1,
    'camila.rojas@example.test',
    '+56 9 0000 0001',
    '56900000001',
    '2026-06-24 10:00:00'
  ),
  (
    1002,
    'case-1002',
    '56900000002',
    'Diego Pérez',
    'phone-002',
    'sac',
    'pending',
    'normal',
    'customer_service',
    0,
    1,
    'awaiting_customer_reply',
    0,
    'active',
    '5002',
    2,
    'INV-1002',
    'n8n_vw_hub_cases',
    1002,
    1,
    '2026-06-24 09:45:00',
    '2026-06-24 09:30:00',
    '2026-06-24 09:45:00',
    NULL,
    1,
    'Quedo atento al correo para continuar',
    2,
    'diego.perez@example.test',
    '+56 9 0000 0002',
    '56900000002',
    '2026-06-24 09:30:00'
  ),
  (
    1003,
    'case-1003',
    '56900000001',
    'Camila Rojas',
    'phone-001',
    'ventas',
    'open',
    'high',
    'onboarding',
    1,
    0,
    'email_requested',
    0,
    'active',
    NULL,
    NULL,
    NULL,
    'n8n_vw_hub_cases',
    1003,
    1,
    '2026-06-24 11:15:00',
    '2026-06-24 11:00:00',
    '2026-06-24 11:15:00',
    NULL,
    1,
    'Para continuar necesito tu correo',
    1,
    NULL,
    '+56 9 0000 0001',
    '56900000001',
    '2026-06-24 11:00:00'
  ),
  (
    1004,
    'case-1004',
    '56900000002',
    'Diego Pérez',
    'phone-002',
    'ventas',
    'open',
    'high',
    'onboarding',
    1,
    0,
    'creation_offered',
    0,
    'active',
    NULL,
    NULL,
    NULL,
    'n8n_vw_hub_cases',
    1004,
    1,
    '2026-06-24 12:15:00',
    '2026-06-24 12:00:00',
    '2026-06-24 12:15:00',
    NULL,
    1,
    'No encontre una cuenta con ese correo',
    2,
    NULL,
    '+56 9 0000 0002',
    '56900000002',
    '2026-06-24 12:00:00'
  ),
  (
    1005,
    'case-1005',
    '56900000002',
    'Empresa Test',
    'phone-003',
    'ventas',
    'open',
    'urgent',
    'onboarding',
    1,
    1,
    'linked_to_customer',
    0,
    'active',
    NULL,
    2,
    NULL,
    'n8n_vw_hub_cases',
    1005,
    1,
    '2026-06-24 13:15:00',
    '2026-06-24 13:00:00',
    '2026-06-24 13:15:00',
    NULL,
    3,
    'Cuenta vinculada a cliente existente',
    3,
    'compras@example.test',
    '+56 9 0000 0002',
    '56900000002',
    '2026-06-24 13:00:00'
  )
ON DUPLICATE KEY UPDATE
  active_case_key = VALUES(active_case_key),
  wa_id = VALUES(wa_id),
  contact_name = VALUES(contact_name),
  phone_number_id = VALUES(phone_number_id),
  department = VALUES(department),
  status = VALUES(status),
  priority = VALUES(priority),
  service_code = VALUES(service_code),
  requires_human = VALUES(requires_human),
  bot_replied = VALUES(bot_replied),
  final_action = VALUES(final_action),
  ai_blocked = VALUES(ai_blocked),
  lifecycle_status = VALUES(lifecycle_status),
  id_order = VALUES(id_order),
  id_customer = VALUES(id_customer),
  invoice_number = VALUES(invoice_number),
  source_table = VALUES(source_table),
  source_id = VALUES(source_id),
  whatsapp_window_open = VALUES(whatsapp_window_open),
  last_message_at = VALUES(last_message_at),
  created_at = VALUES(created_at),
  updated_at = VALUES(updated_at),
  closed_at = VALUES(closed_at),
  message_count = VALUES(message_count),
  last_message = VALUES(last_message),
  contact_id = VALUES(contact_id),
  email = VALUES(email),
  phone = VALUES(phone),
  phone_normalized = VALUES(phone_normalized),
  first_message_at = VALUES(first_message_at);

INSERT INTO n8n_conversation_messages (
  id,
  conversation_case_id,
  message_id,
  wa_id,
  phone_number_id,
  direction,
  message_direction,
  message_type,
  message_text,
  text,
  body,
  message,
  content,
  raw_text,
  final_action,
  status,
  intent,
  department,
  occurred_at,
  created_at,
  updated_at,
  source_table,
  source_id,
  provider_message_id,
  technical_origin,
  id_order,
  id_customer,
  invoice_number
)
VALUES
  (
    1,
    1001,
    'msg-1001-1',
    '56900000001',
    'phone-001',
    'inbound',
    'inbound',
    'text',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'manual_operator_reply',
    'delivered',
    'quote_requested',
    'ventas',
    '2026-06-24 10:05:00',
    '2026-06-24 10:05:00',
    '2026-06-24 10:05:00',
    'n8n_conversation_messages',
    1,
    'provider-1001-1',
    'legacy_n8n',
    '5001',
    1,
    'INV-1001'
  ),
  (
    2,
    1001,
    'msg-1001-2',
    '56900000001',
    'phone-001',
    'outbound',
    'outbound',
    'text',
    'Te comparto una cotización preliminar',
    'Te comparto una cotización preliminar',
    'Te comparto una cotización preliminar',
    'Te comparto una cotización preliminar',
    'Te comparto una cotización preliminar',
    'Te comparto una cotización preliminar',
    'manual_operator_reply',
    'sent',
    'sales_followup',
    'ventas',
    '2026-06-24 10:10:00',
    '2026-06-24 10:10:00',
    '2026-06-24 10:10:00',
    'n8n_conversation_messages',
    2,
    'provider-1001-2',
    'legacy_n8n',
    '5001',
    1,
    'INV-1001'
  ),
  (
    3,
    1002,
    'msg-1002-1',
    '56900000002',
    'phone-002',
    'inbound',
    'inbound',
    'text',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'manual_operator_reply',
    'delivered',
    'request_email',
    'sac',
    '2026-06-24 09:35:00',
    '2026-06-24 09:35:00',
    '2026-06-24 09:35:00',
    'n8n_conversation_messages',
    3,
    'provider-1002-1',
    'legacy_n8n',
    '5002',
    2,
    'INV-1002'
  ),
  (
    4,
    1003,
    'msg-1003-1',
    '56900000001',
    'phone-001',
    'inbound',
    'inbound',
    'text',
    'Mi correo es camila.rojas@example.test',
    'Mi correo es camila.rojas@example.test',
    'Mi correo es camila.rojas@example.test',
    'Mi correo es camila.rojas@example.test',
    'Mi correo es camila.rojas@example.test',
    'Mi correo es camila.rojas@example.test',
    'manual_operator_reply',
    'delivered',
    'email_provided',
    'ventas',
    '2026-06-24 11:05:00',
    '2026-06-24 11:05:00',
    '2026-06-24 11:05:00',
    'n8n_conversation_messages',
    4,
    'provider-1003-1',
    'legacy_n8n',
    NULL,
    NULL,
    NULL
  ),
  (
    5,
    1004,
    'msg-1004-1',
    '56900000002',
    'phone-002',
    'inbound',
    'inbound',
    'text',
    'Si, créala',
    'Si, créala',
    'Si, créala',
    'Si, créala',
    'Si, créala',
    'Si, créala',
    'manual_operator_reply',
    'delivered',
    'creation_confirmed',
    'ventas',
    '2026-06-24 12:05:00',
    '2026-06-24 12:05:00',
    '2026-06-24 12:05:00',
    'n8n_conversation_messages',
    5,
    'provider-1004-1',
    'legacy_n8n',
    NULL,
    NULL,
    NULL
  )
ON DUPLICATE KEY UPDATE
  message_id = VALUES(message_id),
  wa_id = VALUES(wa_id),
  phone_number_id = VALUES(phone_number_id),
  direction = VALUES(direction),
  message_direction = VALUES(message_direction),
  message_type = VALUES(message_type),
  message_text = VALUES(message_text),
  text = VALUES(text),
  body = VALUES(body),
  message = VALUES(message),
  content = VALUES(content),
  raw_text = VALUES(raw_text),
  final_action = VALUES(final_action),
  status = VALUES(status),
  intent = VALUES(intent),
  department = VALUES(department),
  occurred_at = VALUES(occurred_at),
  created_at = VALUES(created_at),
  updated_at = VALUES(updated_at),
  source_table = VALUES(source_table),
  source_id = VALUES(source_id),
  provider_message_id = VALUES(provider_message_id),
  technical_origin = VALUES(technical_origin),
  id_order = VALUES(id_order),
  id_customer = VALUES(id_customer),
  invoice_number = VALUES(invoice_number);

INSERT INTO n8n_wa_inbound_messages (
  id,
  conversation_case_id,
  message_id,
  wa_id,
  phone_number_id,
  direction,
  message_direction,
  message_type,
  message_text,
  text,
  body,
  message,
  content,
  raw_text,
  final_action,
  status,
  intent,
  department,
  occurred_at,
  created_at,
  updated_at,
  source_table,
  source_id,
  provider_message_id,
  technical_origin,
  id_order,
  id_customer,
  invoice_number
)
VALUES
  (
    1,
    1001,
    'inbound-1001-1',
    '56900000001',
    'phone-001',
    'inbound',
    'inbound',
    'text',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'Hola, necesito ayuda con mi cotización',
    'manual_operator_reply',
    'delivered',
    'quote_requested',
    'ventas',
    '2026-06-24 10:05:00',
    '2026-06-24 10:05:00',
    '2026-06-24 10:05:00',
    'n8n_wa_inbound_messages',
    1,
    'provider-inbound-1001-1',
    'legacy_n8n',
    '5001',
    1,
    'INV-1001'
  ),
  (
    2,
    1002,
    'inbound-1002-1',
    '56900000002',
    'phone-002',
    'inbound',
    'inbound',
    'text',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'Hola, me puedes escribir al correo?',
    'manual_operator_reply',
    'delivered',
    'request_email',
    'sac',
    '2026-06-24 09:35:00',
    '2026-06-24 09:35:00',
    '2026-06-24 09:35:00',
    'n8n_wa_inbound_messages',
    2,
    'provider-inbound-1002-1',
    'legacy_n8n',
    '5002',
    2,
    'INV-1002'
  )
ON DUPLICATE KEY UPDATE
  message_id = VALUES(message_id),
  wa_id = VALUES(wa_id),
  phone_number_id = VALUES(phone_number_id),
  direction = VALUES(direction),
  message_direction = VALUES(message_direction),
  message_type = VALUES(message_type),
  message_text = VALUES(message_text),
  text = VALUES(text),
  body = VALUES(body),
  message = VALUES(message),
  content = VALUES(content),
  raw_text = VALUES(raw_text),
  final_action = VALUES(final_action),
  status = VALUES(status),
  intent = VALUES(intent),
  department = VALUES(department),
  occurred_at = VALUES(occurred_at),
  created_at = VALUES(created_at),
  updated_at = VALUES(updated_at),
  source_table = VALUES(source_table),
  source_id = VALUES(source_id),
  provider_message_id = VALUES(provider_message_id),
  technical_origin = VALUES(technical_origin),
  id_order = VALUES(id_order),
  id_customer = VALUES(id_customer),
  invoice_number = VALUES(invoice_number);

INSERT INTO ps_orders (
  id,
  id_order,
  id_customer,
  invoice_number,
  reference,
  order_reference,
  email,
  status,
  total_paid,
  customer_name,
  payment,
  date_upd
)
VALUES
  (1, 5001, 1, 'INV-1001', 'REF-1001', 'REF-1001', 'camila.rojas@example.test', 'paid', 49990.00, 'Camila Rojas', 'transfer', '2026-06-24 10:00:00'),
  (2, 5002, 2, 'INV-1002', 'REF-1002', 'REF-1002', 'diego.perez@example.test', 'pending', 29990.00, 'Diego Pérez', 'card', '2026-06-24 09:20:00')
ON DUPLICATE KEY UPDATE
  id_order = VALUES(id_order),
  id_customer = VALUES(id_customer),
  invoice_number = VALUES(invoice_number),
  reference = VALUES(reference),
  order_reference = VALUES(order_reference),
  email = VALUES(email),
  status = VALUES(status),
  total_paid = VALUES(total_paid),
  customer_name = VALUES(customer_name),
  payment = VALUES(payment),
  date_upd = VALUES(date_upd);

