INSERT INTO crm_customer_onboarding (
  conversation_case_id,
  wa_id,
  state,
  pending_action,
  pending_customer_confirmation,
  email,
  firstname,
  lastname,
  customer_id,
  customer_platform_origin,
  link_status,
  last_decision_id,
  last_tool_name,
  last_tool_status,
  last_tool_result_json,
  last_response_text,
  reason,
  confidence,
  warnings_json,
  context_json
)
VALUES
  (
    '1003',
    '56900000001',
    'email_requested',
    'lookup_customer',
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'seed-1003',
    NULL,
    NULL,
    JSON_OBJECT(),
    'Para continuar necesito el correo asociado a tu cuenta.',
    'Email is required to continue.',
    0.5000,
    JSON_ARRAY(),
    JSON_OBJECT('scenario', 'email_requested')
  ),
  (
    '1004',
    '56900000002',
    'creation_offered',
    'create_customer',
    1,
    'diego.perez@example.test',
    'Diego',
    'Pérez',
    NULL,
    NULL,
    NULL,
    'seed-1004',
    NULL,
    NULL,
    JSON_OBJECT(),
    'No encontre una cuenta con ese correo. Quieres que cree una cuenta nueva?',
    'No exact customer match was found.',
    0.6500,
    JSON_ARRAY(),
    JSON_OBJECT('scenario', 'creation_offered')
  ),
  (
    '1005',
    '56900000002',
    'customer_linked',
    NULL,
    0,
    'compras@example.test',
    'Empresa',
    'Test',
    '3',
    'pos',
    'confirmed',
    'seed-1005',
    'lookup_customer_by_email',
    'executed',
    JSON_OBJECT('status', 'found'),
    'Encontré tu cuenta a nombre de Empresa Test. Continuemos.',
    'Conversation already has a linked customer.',
    0.9200,
    JSON_ARRAY(),
    JSON_OBJECT('scenario', 'already_linked')
  )
ON DUPLICATE KEY UPDATE
  state = VALUES(state),
  pending_action = VALUES(pending_action),
  pending_customer_confirmation = VALUES(pending_customer_confirmation),
  email = VALUES(email),
  firstname = VALUES(firstname),
  lastname = VALUES(lastname),
  customer_id = VALUES(customer_id),
  customer_platform_origin = VALUES(customer_platform_origin),
  link_status = VALUES(link_status),
  last_decision_id = VALUES(last_decision_id),
  last_tool_name = VALUES(last_tool_name),
  last_tool_status = VALUES(last_tool_status),
  last_tool_result_json = VALUES(last_tool_result_json),
  last_response_text = VALUES(last_response_text),
  reason = VALUES(reason),
  confidence = VALUES(confidence),
  warnings_json = VALUES(warnings_json),
  context_json = VALUES(context_json);

INSERT INTO customer_conversation_link (
  customer_id,
  conversation_case_id,
  link_status,
  link_source,
  confidence,
  linked_at
)
VALUES
  ('1', '1001', 'confirmed', 'ai_sdr', 'high', '2026-06-24 10:12:00'),
  ('2', '1004', 'confirmed', 'ai_sdr', 'high', '2026-06-24 12:12:00'),
  ('3', '1005', 'confirmed', 'operator', 'medium', '2026-06-24 13:12:00')
ON DUPLICATE KEY UPDATE
  customer_id = VALUES(customer_id),
  link_status = VALUES(link_status),
  link_source = VALUES(link_source),
  confidence = VALUES(confidence),
  linked_at = VALUES(linked_at);

